### ISSUE TITLE
دریافت ارور Could not get resource 

### ISSUE THREAD

**Issue by m1faridi** [myketstore/myket-billing-client#1]
FAILURE: Build completed with 8 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsGoogle_playDebug'.
> Could not resolve all files for configuration ':app:google_playDebugCompileClasspath'.
   > Could not resolve com.github.myketstore:myket-billing-client:v1.1.
     Required by:
         project :app
      > Could not resolve com.github.myketstore:myket-billing-client:v1.1.
         > Could not get resource 'https://jcenter.bintray.com/com/github/myketstore/myket-billing-client/v1.1/myket-billing-client-v1.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/github/myketstore/myket-billing-client/v1.1/myket-billing-client-v1.1.pom'. Received status code 403 from server: Forbidden

**Comment by m1faridi** [comment]
این رو پروژه من از قبل اضافه شده من از کلی کتابخونه استفاده میکنم اما این کتابخونه اضافه نمیشه

`ext {
    sourceCompatibility = JavaVersion.VERSION_1_8
}// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = '1.4.32'
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }

    dependencies {
        classpath "com.android.tools.build:gradle:7.0.3"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

**Comment by AhM0D** [comment]
Fixed now in [v1.2](https://github.com/myketstore/myket-billing-client/releases/tag/v1.2)

**Comment by m1faridi** [comment]
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:google_playDebugCompileClasspath'.
این v1.4 نسخه ارور داره

**Comment by AhM0D** [comment]
سلام وقتتون بخیر 
یک تغییری در نامگزاری نسخه هامون بوجود آوردیم به جای v1.4 از 1.4 استفاده کنید.

**Comment by m1faridi** [comment]
ممنون
