### ISSUE TITLE
خرید درون از گوگل پلی

### ISSUE THREAD

**Issue by m1faridi** [myketstore/myket-billing-client#2]
سلام 
یه سوال  گوگل چند ماه قبل به توسعه دهنده ها ایمیل داد که کتابخونه خرید درون رو به نسخه ۴ اپدیت کنن و برنامه هایی که از کتابخونه قدیمی استفاده میکنن دیگه اپدیت نمیکنن
و ما از com.android.billingclient:billing:4.0.0  گوگل استفاده کردیم
ورژن گوگل پلی این لایبرری چند هستش ؟

**Comment by AhM0D** [comment]
سلام 
در حال حاضراین کتابخانه به پیاده سازی قدیمی پرداخت گوگل نزدیک است و از نسخه ۴ آن پشتیبانی نمی‌کند، اما می‌توانید از این کتابخانه برای پیاده‌سازی پرداخت مایکت و دیگر فروشگاه های داخلی چون بازار استفاده کنید.
