### ISSUE TITLE
force stop when wrong public key

### ISSUE THREAD

**Issue by saeed74** [myketstore/myket-billing-client#3]
سلام وقت بخیر. نسخه لایبراری 1.3 
وقتی پابلیک key رو اشتباه وارد کنیم اپ کرش میکنه هنگام برگشت از درگاه مایکت.

```
lang.IllegalArgumentException: java.security.spec.InvalidKeySpecException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key
        at ir.myket.billingclient.util.Security.generatePublicKey(Security.java:82)
        at ir.myket.billingclient.util.Security.verifyPurchase(Security.java:62)
        at ir.myket.billingclient.util.IAB$1.onReceiveResult(IAB.java:92)
        at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
```
        

درسته ک اشتباه سمت کاربر هست اما قشنگ تره که خطا بده و کرش نکنه.
من چون لایبراری رو مستقیم ادد دیپندنسی کردم با یک try catch مدیریت کردم این موضوع رو داخل فایل Security.java در پوشه utils

        
```
           public static boolean verifyPurchase(String base64PublicKey, String signedData, String signature) {
        if (TextUtils.isEmpty(signedData) || TextUtils.isEmpty(base64PublicKey) ||
                TextUtils.isEmpty(signature)) {
            Log.e(TAG, "Purchase verification failed: missing data.");
            return false;
        }

        try{
            PublicKey key = Security.generatePublicKey(base64PublicKey);
            return Security.verify(key, signedData, signature);
        }catch (Exception e){
            Log.e(TAG, "Purchase verification failed: maybe wrong RSA Public Key");
            return false;
        }

    }
```
        
خوبه ک اصلاح کنید این مورد رو.
 باتشکر

**Comment by AhM0D** [comment]
سلام وقتتون بخیر،

  نادرست بودن public key سمت توسعه‌دهنده است و کاربرها را تحت تاثیر قرار نمی‌دهد و از طرفی در هنگام پیاده‌سازی و تست آن توسط توسعه‌دهنده باید مشاهده شود تا توسعه دهنده به اشتباه بودن آن پی ببرد و مشکل را قبل از گرفتن خروجی نهایی حل کند.

**Comment by saeed74** [comment]
وقت بخیر، درسته متوجه هستم سمت توسعه دهنده هست. ما چون سرویس اپ ساز ارائه میدیم و B2B هستیم نیاز بود این مورد رو به کاربر B بدون کرش کردن انتقال بدیم چون کاربر ما سمت پنل این مورد رو وارد میکنه.
(گفتم این موضوع رو بگم شاید گفتنش خالی از لطف نباشه.)
به هر حال ممنون.
