### ISSUE TITLE
Execution failed for task ':app:lintVitalMyketRelease'

### ISSUE THREAD

**Issue by simonsalamon** [myketstore/myket-billing-client#5]
موقع خروجی گرفتن با sdk جاوا به این ارور خوردم 

`
Execution failed for task :app:lintVitalMyketRelease.
> Could not resolve all files for configuration :app:lintClassPath.
   > Could not find kotlin-compiler.jar (com.android.tools.external.com-intellij:kotlin-compiler:26.3.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/26.3.3/kotlin-compiler-26.3.3.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
`

**Comment by AhM0D** [comment]
این مشکل در build شما وجود دارد و ارتباطی با sdk مایکت ندارد
