### ISSUE TITLE
حل مشکل  در build.gradle.kts 

### ISSUE THREAD

**Issue by androidkade11** [myketstore/myket-billing-client#9]
سلام 
کسانی که از build.gradle.kts استفاده میکنن defaultConfig رو به این صورت پیاده سازی کنید :

val marketApplicationId = "ir.mservices.market"
        val marketBindAddress = "ir.mservices.market.InAppBillingService.BIND"
        manifestPlaceholders.apply {
            this["marketApplicationId"] = marketApplicationId
            this["marketBindAddress"] = marketBindAddress
            this["marketPermission"] = "${marketApplicationId}.BILLING"
        }
        buildConfigField(
            "String",
            "IAB_PUBLIC_KEY",
            "YOUR_KEY"
        )

**Comment by komeilkamal** [comment]
Thank you for your attention. It Added to Myket's technical documentation.
